---
- name: Install required packages
  apt:
    update_cache: yes
    name:
      - ntp
      - apt-transport-https
      - gnupg2
      - ca-certificates
      - software-properties-common
      - open-iscsi
    state: present

- name: Add Kubernetes Apt repo key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes to Apt repo
  copy:
    content: >-
      deb https://apt.kubernetes.io/ kubernetes-xenial main
    dest: /etc/apt/sources.list.d/kubernetes.list
    mode: '0644'

- name: Update Apt cache
  apt:
    update_cache: yes

- name: Get package info
  command: sh -c "apt-cache madison kubelet | grep {{ kube_version }} | awk '{print $3}'"
  register: kube_pkg_info
  changed_when: no

- name: Set package version
  set_fact:
    kube_pkg_version: "{{ kube_pkg_info.stdout_lines[0]}}"

- name: Install Kubernetes packages
  apt:
    update_cache: no
    name:
      - kubeadm={{ kube_pkg_version }}
      - kubelet={{ kube_pkg_version }}
      - kubectl={{ kube_pkg_version }}
    state: present

- include_tasks: "install-Debian-containerd.yml"
  when: kube_container_runtime == "containerd"

- meta: flush_handlers
