---
- name: reload modules
  systemd:
    state: restarted
    name: systemd-modules-load.service

- name: reload sysctl
  systemd:
    state: restarted
    name: systemd-sysctl.service

- name: reload kubelet
  systemd:
    daemon_reload: yes
    state: restarted
    name: kubelet.service
